version: '3.1'
volumes:
  data:
  arquivos:
services: 
  web:
    build: .
    ports: 
      - 5002:5000
    volumes:
      - .:/project
      - ./arquivos:/project
    depends_on:
      - db
    networks: 
      - net
      - server
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: data
      MYSQL_ROOT_PASSWORD: rootroot
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql/
    networks: 
      - server
  workdb:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 81:80
    environment: 
      PMA_ARBITRARY: 1
    networks: 
      - server

networks:
  server:
    driver: bridge
  net:
    external: 
      name: tipsta-network


